//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPhotos.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyPhotos.Language.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adınız.
        /// </summary>
        public static string Adınız {
            get {
                return ResourceManager.GetString("Adınız", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad alanı 5 karakterden kısa veya 20 karakterden uzun olamaz..
        /// </summary>
        public static string AdSınırlama {
            get {
                return ResourceManager.GetString("AdSınırlama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktifleştirme Butonu.
        /// </summary>
        public static string AktifButon {
            get {
                return ResourceManager.GetString("AktifButon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnaSayfa.
        /// </summary>
        public static string AnaSayfa {
            get {
                return ResourceManager.GetString("AnaSayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Böyle bir aktifleştirme kodu mevcut değil..
        /// </summary>
        public static string Böyle_bir_aktifleştirme_kodu_mevcut_değil_ {
            get {
                return ResourceManager.GetString("Böyle bir aktifleştirme kodu mevcut değil.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış.
        /// </summary>
        public static string Cıkıs {
            get {
                return ResourceManager.GetString("Cıkıs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğum tarihi alanı boş geçilemez..
        /// </summary>
        public static string DoğumTarihiKontrol {
            get {
                return ResourceManager.GetString("DoğumTarihiKontrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Bülten Üyeliği.
        /// </summary>
        public static string EBülten {
            get {
                return ResourceManager.GetString("EBülten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen email formatında değer girin..
        /// </summary>
        public static string EmailFormat {
            get {
                return ResourceManager.GetString("EmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email alanı 5-35 karakter aralığında olmalıdır..
        /// </summary>
        public static string EmailSınırlama {
            get {
                return ResourceManager.GetString("EmailSınırlama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Beğenilenler.
        /// </summary>
        public static string EnBeğenilenler {
            get {
                return ResourceManager.GetString("EnBeğenilenler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eposta.
        /// </summary>
        public static string Eposta {
            get {
                return ResourceManager.GetString("Eposta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu e-posta adresi başka bir kullanıcı tarafından kullanılıyor..
        /// </summary>
        public static string EpostaKullanılıyor {
            get {
                return ResourceManager.GetString("EpostaKullanılıyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GirisYap.
        /// </summary>
        public static string GirisYap {
            get {
                return ResourceManager.GetString("GirisYap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönder.
        /// </summary>
        public static string Gönder {
            get {
                return ResourceManager.GetString("Gönder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        public static string Hakkımızda {
            get {
                return ResourceManager.GetString("Hakkımızda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoşgeldin!.
        /// </summary>
        public static string Hoşgeldin {
            get {
                return ResourceManager.GetString("Hoşgeldin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoriler.
        /// </summary>
        public static string Kategoriler {
            get {
                return ResourceManager.GetString("Kategoriler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt.
        /// </summary>
        public static string Kayıt {
            get {
                return ResourceManager.GetString("Kayıt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kullanıcı adı başka bir kullanıcı tarafından kullanılıyor..
        /// </summary>
        public static string KullanıcıAdıKullanılıyor {
            get {
                return ResourceManager.GetString("KullanıcıAdıKullanılıyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adınız.
        /// </summary>
        public static string KullanıcıAdınız {
            get {
                return ResourceManager.GetString("KullanıcıAdınız", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullancı Adı ve Şifre Uyuşmuyor..
        /// </summary>
        public static string KullanıcıadıŞifreUyumsuz {
            get {
                return ResourceManager.GetString("KullanıcıadıŞifreUyumsuz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı alanı 5 karakterden kısa veya 20 karakterden uzun olamaz..
        /// </summary>
        public static string KullanıcıAdıSınırlama {
            get {
                return ResourceManager.GetString("KullanıcıAdıSınırlama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Aktif değil.Lütfen e-posta adresinizden hesabınızı aktifleştirin..
        /// </summary>
        public static string KullanıcıAktifDeğil {
            get {
                return ResourceManager.GetString("KullanıcıAktifDeğil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı bulunamıyor..
        /// </summary>
        public static string KullanıcıBulunamıyor {
            get {
                return ResourceManager.GetString("KullanıcıBulunamıyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı güncellenemedi..
        /// </summary>
        public static string KullanıcıGüncellenemedi_ {
            get {
                return ResourceManager.GetString("KullanıcıGüncellenemedi.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı silinemedi..
        /// </summary>
        public static string KullanıcıSilinemedi {
            get {
                return ResourceManager.GetString("KullanıcıSilinemedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı zaten aktifleştirilmiş..
        /// </summary>
        public static string KullanıcıZatenAktifleştirilmiş_ {
            get {
                return ResourceManager.GetString("KullanıcıZatenAktifleştirilmiş.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        public static string Şifre {
            get {
                return ResourceManager.GetString("Şifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre alanları birbiri ile uyuşmuyor..
        /// </summary>
        public static string ŞifreKontrol {
            get {
                return ResourceManager.GetString("ŞifreKontrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre alanı 5 karakterden kısa veya 20 karakterden uzun olamaz..
        /// </summary>
        public static string ŞifreSınırlama {
            get {
                return ResourceManager.GetString("ŞifreSınırlama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ŞifreTekrar.
        /// </summary>
        public static string ŞifreTekrar {
            get {
                return ResourceManager.GetString("ŞifreTekrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Eklenenler.
        /// </summary>
        public static string SonEklenenler {
            get {
                return ResourceManager.GetString("SonEklenenler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyadınız.
        /// </summary>
        public static string Soyadınız {
            get {
                return ResourceManager.GetString("Soyadınız", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyad alanı 5 karakterden kısa veya 20 karakterden uzun olamaz..
        /// </summary>
        public static string SoyadıSınırlama {
            get {
                return ResourceManager.GetString("SoyadıSınırlama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Ol.
        /// </summary>
        public static string ÜyeOl {
            get {
                return ResourceManager.GetString("ÜyeOl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetim.
        /// </summary>
        public static string Yonetim {
            get {
                return ResourceManager.GetString("Yonetim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Yorumlar {
            get {
                return ResourceManager.GetString("Yorumlar", resourceCulture);
            }
        }
    }
}
